except Exception as e:
    print("inserisci un valore valido")
    print(e)